version: "3.9"
services:
  golang:
    build: .
    tty: true
    volumes:
      - ./code:/code
    ports:
      - "8080:8000"
  mysql:
    platform: 'linux/x86_64'
    image: mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - TZ=Asia/Taipei
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mycnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
  redis:
    platform: 'linux/x86_64'
    image: redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

